/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dealer;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author QCTFW
 */
public class CrudMerk extends javax.swing.JFrame {
    
    Connection cn = koneksi.getKoneksi();
    DefaultTableModel tabModel;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form CrudMerk
     */
    public CrudMerk() {
        initComponents();
        tampilanTabel();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemerk = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtmerek = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelola Merk");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KELOLA MEREK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nama Merek");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 40));

        tablemerk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tablemerk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemerkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablemerk);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 150, 140));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, 10));

        txtmerek.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        txtmerek.setBorder(null);
        txtmerek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmerekKeyTyped(evt);
            }
        });
        jPanel1.add(txtmerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 40));

        btnsubmit.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 30));

        btnhapus.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 80, 30));

        jButton1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    void tampilanTabel(){
        Object[] judul = {"No", "Nama Merk"};
        tabModel = new DefaultTableModel(null, judul){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tablemerk.setModel(tabModel);
        tablemerk.getColumnModel().getColumn(0).setMinWidth(WIDTH-110);
        tablemerk.getColumnModel().getColumn(1).setMinWidth(WIDTH+110);
    }
    
    void reset(){
        txtmerek.setText("");
        btnsubmit.setText("SUBMIT");
    }
    
    void tampilData() {
        try {
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tb_merk ORDER BY id_merk ASC");
            int no = 1;
            while (rs.next()) {
                Object[] data = {
                    no++,
                    rs.getString("merk")
                };
                tabModel.addRow(data);
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tampil Data Error\n" + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        if ( !( txtmerek.getText().length() <= 20 && !txtmerek.getText().equals("") ) ) {
            JOptionPane.showMessageDialog(null, "Penulisan nama merk tidak valid\nPanjang Maksimal adalah 20 karakter", "Validasi", JOptionPane.INFORMATION_MESSAGE);
            reset();
        }
        else {
            try {
                String sql;
                boolean isSubmit = btnsubmit.getText().equals("SUBMIT");
                if (isSubmit) {
                    sql = "INSERT INTO tb_merk VALUES(null,'" + txtmerek.getText() + "')";
                }
                else {
                    sql = "UPDATE tb_merk SET merk = '" + txtmerek.getText() + "' WHERE merk = '" + tabModel.getValueAt(tablemerk.getSelectedRow(), 1).toString() + "'";
                }
                st = cn.createStatement();
                st.executeUpdate(sql);
                if (isSubmit) {
                    JOptionPane.showMessageDialog(null, "Berhasil Diinput!");   
                }
                else {
                    JOptionPane.showMessageDialog(null, "Berhasil Diupdate!");
                }
                tampilData();
                reset();
            }
            catch (SQLException e) {
                if (e.getMessage().contains("Duplicate entry")) {
                    JOptionPane.showMessageDialog(null, "Nama merk ini sudah dipakai!", "Validasi", JOptionPane.WARNING_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Gagal\n Error: " + e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
                }   
            }
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        if (btnsubmit.getText().equals("UPDATE")) {
            try {
                st = cn.createStatement();
                rs = st.executeQuery("SELECT merk FROM tampil_stok WHERE merk = '" + txtmerek.getText() + "'");
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Tidak bisa dihapus karena merek ini sudah dipakai\nHarap hapus unit kendaraan yang menggunakan merk ini lalu coba lagi.", "Validasi", JOptionPane.WARNING_MESSAGE);
                }
                else {
                    try {
                        int jawab = JOptionPane.showConfirmDialog(null, "Ingin Menghapus Field Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                        if (jawab == 0) {
                            st = cn.createStatement();
                            st.executeUpdate("DELETE FROM tb_merk WHERE merk='" + tabModel.getValueAt(tablemerk.getSelectedRow(), 1).toString() + "'");
                            tampilData();
                            reset();
                            JOptionPane.showMessageDialog(null, "Berhasil Dihapus!");
                        }
                    }
                    catch (SQLException e) {
                        e.printStackTrace();
                    }
                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            
            
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tablemerkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemerkMouseClicked
        txtmerek.setText(tabModel.getValueAt(tablemerk.getSelectedRow(), 1).toString());
        btnsubmit.setText("UPDATE");
    }//GEN-LAST:event_tablemerkMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new CrudStok().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void txtmerekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmerekKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            btnsubmitActionPerformed(null);
        }
    }//GEN-LAST:event_txtmerekKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudMerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudMerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudMerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudMerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudMerk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablemerk;
    private javax.swing.JTextField txtmerek;
    // End of variables declaration//GEN-END:variables
}
