/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dealer;

import java.awt.Color;

/**
 *
 * @author QCTFW
 */
public class menu extends javax.swing.JFrame {

    Color exit = new Color(204,204,204);
    Color hover = new Color(240,240,240);
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new javax.swing.JPanel();
        panel_transaksi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_stok = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel_report = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pilih Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_utama.setBackground(new java.awt.Color(255, 255, 255));
        panel_utama.setPreferredSize(new java.awt.Dimension(720, 240));
        panel_utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_transaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_transaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_transaksiMouseExited(evt);
            }
        });
        panel_transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 32)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TRANSAKSI");
        panel_transaksi.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 180, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealer/ic_transaction.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(34, 32));
        jLabel3.setMinimumSize(new java.awt.Dimension(34, 32));
        jLabel3.setPreferredSize(new java.awt.Dimension(34, 32));
        panel_transaksi.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 130));

        panel_utama.add(panel_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 180));

        panel_stok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_stokMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_stokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_stokMouseExited(evt);
            }
        });
        panel_stok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 28)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("KELOLA STOK");
        panel_stok.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealer/ic_garage.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(34, 32));
        jLabel6.setMinimumSize(new java.awt.Dimension(34, 32));
        jLabel6.setPreferredSize(new java.awt.Dimension(34, 32));
        panel_stok.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 130));

        panel_utama.add(panel_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 180, 180));

        panel_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_reportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_reportMouseExited(evt);
            }
        });
        panel_report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 28)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LAPORAN");
        panel_report.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, 50));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealer/ic_report.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(34, 32));
        jLabel8.setMinimumSize(new java.awt.Dimension(34, 32));
        jLabel8.setPreferredSize(new java.awt.Dimension(34, 32));
        panel_report.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 130));

        panel_utama.add(panel_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 180, 180));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Azhar At Zauhar Dripana - RPL XI-3");
        panel_utama.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 180, -1));

        getContentPane().add(panel_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_stokMouseClicked
        new CrudStok().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panel_stokMouseClicked

    private void panel_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_transaksiMouseClicked
        new CrudTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panel_transaksiMouseClicked

    private void panel_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_reportMouseClicked
        new CrudLaporan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panel_reportMouseClicked

    private void panel_transaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_transaksiMouseEntered
        panel_transaksi.setBackground(hover);
    }//GEN-LAST:event_panel_transaksiMouseEntered

    private void panel_transaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_transaksiMouseExited
        panel_transaksi.setBackground(exit);
    }//GEN-LAST:event_panel_transaksiMouseExited

    private void panel_stokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_stokMouseEntered
        panel_stok.setBackground(hover);
    }//GEN-LAST:event_panel_stokMouseEntered

    private void panel_stokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_stokMouseExited
        panel_stok.setBackground(exit);
    }//GEN-LAST:event_panel_stokMouseExited

    private void panel_reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_reportMouseEntered
        panel_report.setBackground(hover);
    }//GEN-LAST:event_panel_reportMouseEntered

    private void panel_reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_reportMouseExited
        panel_report.setBackground(exit);
    }//GEN-LAST:event_panel_reportMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panel_report;
    private javax.swing.JPanel panel_stok;
    private javax.swing.JPanel panel_transaksi;
    private javax.swing.JPanel panel_utama;
    // End of variables declaration//GEN-END:variables
}
